version: '3.8'

services:
  server:
    image: nginx:alpine3.17
    ports:
      - ${APP_PORT:-8000}:80
    volumes:
      - ./src:/var/www/html
      - ./docker/8.2/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  php:
    build: ./docker/8.2/php
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    env_file:
      - ./env/mysql.env
    volumes:
      - data:/var/lib/mysql
  composer:
    build: ./docker/8.2/composer
    volumes:
      - ./src:/var/www/html
      
volumes:
  data: