version: '3.8'

services:
  server:
    build: 
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - ${APP_PORT:-8000}:80
    depends_on:
      - php
  php:
    build: 
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    env_file:
      - ./env/mysql.env
    volumes:
      - data:/var/lib/mysql
  composer:
    build: ./docker/composer
    volumes:
      - ./src:/var/www/html
  artisan:
    build: 
      context: .
      dockerfile: ./docker/php/Dockerfile
    entrypoint: ["php", "/var/www/html/artisan"]
    volumes:
      - ./src:/var/www/html
  npm:
    image: node:latest
    volumes:
      - ./src:/var/www/html
    entrypoint: ["npm"]
volumes:
  data: